language: csharp
sudo: required
solution: YY.EventLogReaderAssistant.sln

matrix:
  include:
    - dist: trusty
      mono: none
      dotnet: 3.1.201

before_script:
  - chmod -R a+x ./scripts

script:
  - ./scripts/build.sh
  - ./scripts/runTests.sh

notifications:
  email:
    on_success: change
    on_failure: change